import Foundation

struct Product: Identifiable {
    let id = UUID()
    let slug: String
    let name: String
    let nameEn: String
    let pricePerKg: Int
    let category: String
    let imageName: String
    var isSystemImage: Bool = true
    let wikipediaUrl: String?
    let imageUrl: String?
    
    init(slug: String, name: String, nameEn: String, pricePerKg: Int, category: String, imageName: String = "leaf.fill", isSystemImage: Bool = true, wikipediaUrl: String? = nil, imageUrl: String? = nil) {
        self.slug = slug
        self.name = name
        self.nameEn = nameEn
        self.pricePerKg = pricePerKg
        self.category = category
        self.imageName = imageName
        self.isSystemImage = isSystemImage
        self.wikipediaUrl = wikipediaUrl
        self.imageUrl = imageUrl
    }
}

extension Product {
    static let mockProducts: [Product] = [
        Product(slug: "tomate", name: "Tomate", nameEn: "Tomato", pricePerKg: 800, category: "Légumes-fruits", imageName: "leaf", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Tomate", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tomato_je.jpg/320px-Tomato_je.jpg"),
        Product(slug: "oignon", name: "Oignon", nameEn: "Onion", pricePerKg: 600, category: "Tubercules", imageName: "oignon", isSystemImage: false, wikipediaUrl: "https://fr.wikipedia.org/wiki/Oignon", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Onion_on_White.JPG/320px-Onion_on_White.JPG"),
        Product(slug: "ail", name: "Ail", nameEn: "Garlic", pricePerKg: 1500, category: "Tubercules", imageName: "sparkles", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Ail", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Garlic_press_and_garlic_cloves.jpg/320px-Garlic_press_and_garlic_cloves.jpg"),
        Product(slug: "echalote", name: "Échalote", nameEn: "Shallot", pricePerKg: 1200, category: "Tubercules", imageName: "leaf", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/%C3%89chalote", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Eschalots.jpg/320px-Eschalots.jpg"),
        Product(slug: "carotte", name: "Carotte", nameEn: "Carrot", pricePerKg: 500, category: "Racines", imageName: "carotte", isSystemImage: false, wikipediaUrl: "https://fr.wikipedia.org/wiki/Carotte", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Carrots_at_Ljubljana_Central_Market.JPG/320px-Carrots_at_Ljubljana_Central_Market.JPG"),
        Product(slug: "navet", name: "Navet", nameEn: "Turnip", pricePerKg: 600, category: "Racines", imageName: "carrot.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Navet", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Turnip_2622027.jpg/320px-Turnip_2622027.jpg"),
        Product(slug: "betterave", name: "Betterave", nameEn: "Beetroot", pricePerKg: 700, category: "Racines", imageName: "drop.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Betterave", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Beetroot_jm13247.jpg/320px-Beetroot_jm13247.jpg"),
        Product(slug: "radis", name: "Radis", nameEn: "Radish", pricePerKg: 800, category: "Racines", imageName: "leaf.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Radis", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Radish_3371101_1920.jpg/320px-Radish_3371101_1920.jpg"),
        Product(slug: "pomme-de-terre", name: "Pomme de terre", nameEn: "Potato", pricePerKg: 450, category: "Tubercules", imageName: "pomme_de_terre", isSystemImage: false, wikipediaUrl: "https://fr.wikipedia.org/wiki/Pomme_de_terre", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Patates.jpg/320px-Patates.jpg"),
        Product(slug: "patate-douce", name: "Patate douce", nameEn: "Sweet potato", pricePerKg: 400, category: "Tubercules", imageName: "oval.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Patate_douce", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/SweetPotato.jpg/320px-SweetPotato.jpg"),
        Product(slug: "manioc", name: "Manioc", nameEn: "Cassava", pricePerKg: 350, category: "Tubercules", imageName: "leaf.arrow.triangle.circlepath", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Manioc", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Manihot_esculenta_ds.jpg/320px-Manihot_esculenta_ds.jpg"),
        Product(slug: "igname", name: "Igname", nameEn: "Yam", pricePerKg: 900, category: "Tubercules", imageName: "square.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Igname", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Yamsatmarket.jpg/320px-Yamsatmarket.jpg"),
        Product(slug: "taro", name: "Taro", nameEn: "Taro", pricePerKg: 850, category: "Tubercules", imageName: "circle.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Taro", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Satoimo.jpg/320px-Satoimo.jpg"),
        Product(slug: "gingembre", name: "Gingembre", nameEn: "Ginger", pricePerKg: 1200, category: "Racines", imageName: "flame.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Gingembre", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Ginger_root.jpg/320px-Ginger_root.jpg"),
        Product(slug: "curcuma", name: "Curcuma", nameEn: "Turmeric", pricePerKg: 1400, category: "Racines", imageName: "sun.max.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Curcuma", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Turmeric_rhizome.jpg/320px-Turmeric_rhizome.jpg"),
        Product(slug: "poivron", name: "Poivron", nameEn: "Bell pepper", pricePerKg: 1200, category: "Légumes-fruits", imageName: "bell", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Poivron", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Bell_peppers_multicolored.jpg/320px-Bell_peppers_multicolored.jpg"),
        Product(slug: "piment", name: "Piment", nameEn: "Chili pepper", pricePerKg: 1500, category: "Légumes-fruits", imageName: "flame", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Piment", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Chili_peppers.jpg/320px-Chili_peppers.jpg"),
        Product(slug: "aubergine", name: "Aubergine", nameEn: "Eggplant", pricePerKg: 700, category: "Légumes-fruits", imageName: "capsule.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Aubergine", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/320px-Solanum_melongena_24_08_2012_%281%29.JPG"),
        Product(slug: "gombo", name: "Gombo", nameEn: "Okra", pricePerKg: 800, category: "Légumes-fruits", imageName: "star.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Gombo", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Abelmoschus_esculentus_pods.jpg/320px-Abelmoschus_esculentus_pods.jpg"),
        Product(slug: "concombre", name: "Concombre", nameEn: "Cucumber", pricePerKg: 500, category: "Légumes-fruits", imageName: "oval", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Concombre", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Cucumber_Fruit.jpg/320px-Cucumber_Fruit.jpg"),
        Product(slug: "courgette", name: "Courgette", nameEn: "Zucchini", pricePerKg: 900, category: "Légumes-fruits", imageName: "capsule", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Courgette", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Cucurbita_pepo_courgette.jpg/320px-Cucurbita_pepo_courgette.jpg"),
        Product(slug: "courge", name: "Courge", nameEn: "Squash", pricePerKg: 600, category: "Légumes-fruits", imageName: "circle.grid.cross.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Courge", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Courges_au_marche.jpg/320px-Courges_au_marche.jpg"),
        Product(slug: "citrouille", name: "Citrouille", nameEn: "Pumpkin", pricePerKg: 500, category: "Légumes-fruits", imageName: "circle", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Citrouille", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Great_Pumpkin.jpg/320px-Great_Pumpkin.jpg"),
        Product(slug: "potiron", name: "Potiron", nameEn: "Pumpkin", pricePerKg: 550, category: "Légumes-fruits", imageName: "circle.inset.filled", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Potiron", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Potiron_rouge_vif_d%27Etampes.JPG/320px-Potiron_rouge_vif_d%27Etampes.JPG"),
        Product(slug: "chou", name: "Chou", nameEn: "Cabbage", pricePerKg: 700, category: "Feuilles", imageName: "leaf.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Chou", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Cabbage_and_cross_section_on_white.jpg/320px-Cabbage_and_cross_section_on_white.jpg"),
        Product(slug: "chou-fleur", name: "Chou-fleur", nameEn: "Cauliflower", pricePerKg: 1300, category: "Feuilles", imageName: "cloud.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Chou-fleur", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Cauliflower_isolated.jpg/320px-Cauliflower_isolated.jpg"),
        Product(slug: "brocoli", name: "Brocoli", nameEn: "Broccoli", pricePerKg: 1500, category: "Feuilles", imageName: "tree.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Brocoli", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Broccoli_and_cross_section_edit.jpg/320px-Broccoli_and_cross_section_edit.jpg"),
        Product(slug: "epinard", name: "Épinard", nameEn: "Spinach", pricePerKg: 900, category: "Feuilles", imageName: "leaf", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/%C3%89pinard", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Spinacia_oleracea_Spinach.jpg/320px-Spinacia_oleracea_Spinach.jpg"),
        Product(slug: "laitue", name: "Laitue", nameEn: "Lettuce", pricePerKg: 800, category: "Feuilles", imageName: "wind", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Laitue", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Lettuce_in_a_field.jpg/320px-Lettuce_in_a_field.jpg"),
        Product(slug: "poireau", name: "Poireau", nameEn: "Leek", pricePerKg: 1000, category: "Feuilles", imageName: "line.3.horizontal", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Poireau", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Leek_1.jpg/320px-Leek_1.jpg"),
        Product(slug: "haricot-vert", name: "Haricot vert", nameEn: "Green bean", pricePerKg: 1100, category: "Feuilles", imageName: "line.diagonal", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Haricot_vert", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Phaseolus_vulgaris_green_pods.jpg/320px-Phaseolus_vulgaris_green_pods.jpg"),
        Product(slug: "petit-pois", name: "Petit pois", nameEn: "Green pea", pricePerKg: 1200, category: "Feuilles", imageName: "smallcircle.filled.circle", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Pois", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Peas_in_pod_-_Studio.jpg/320px-Peas_in_pod_-_Studio.jpg"),
        Product(slug: "feve", name: "Fève", nameEn: "Broad bean", pricePerKg: 1000, category: "Feuilles", imageName: "ellipsis.circle.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/F%C3%A8ve", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Broad_bean_pods_and_seeds.jpg/320px-Broad_bean_pods_and_seeds.jpg"),
        Product(slug: "mais", name: "Maïs", nameEn: "Maize", pricePerKg: 400, category: "Céréales & Légumineuses", imageName: "square.grid.3x3.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Ma%C3%AFs", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Corn_on_the_cob.jpg/320px-Corn_on_the_cob.jpg"),
        Product(slug: "ble", name: "Blé", nameEn: "Wheat", pricePerKg: 500, category: "Céréales & Légumineuses", imageName: "chart.bar.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Bl%C3%A9", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Wheat_close-up.jpg/320px-Wheat_close-up.jpg"),
        Product(slug: "riz", name: "Riz", nameEn: "Rice", pricePerKg: 450, category: "Céréales & Légumineuses", imageName: "shippingbox.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Riz", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Rice_grains.jpg/320px-Rice_grains.jpg"),
        Product(slug: "mil", name: "Mil", nameEn: "Millet", pricePerKg: 400, category: "Céréales & Légumineuses", imageName: "circle.grid.2x2.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Mil", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Pearl_millet_Pennisetum_glaucum.jpg/320px-Pearl_millet_Pennisetum_glaucum.jpg"),
        Product(slug: "sorgho", name: "Sorgho", nameEn: "Sorghum", pricePerKg: 450, category: "Céréales & Légumineuses", imageName: "rays", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Sorgho", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Sorghum_bicolor_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-131.jpg/320px-Sorghum_bicolor_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-131.jpg"),
        Product(slug: "fonio", name: "Fonio", nameEn: "Fonio", pricePerKg: 1200, category: "Céréales & Légumineuses", imageName: "sparkle", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Fonio", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Fonio_grains.jpg/320px-Fonio_grains.jpg"),
        Product(slug: "niebe", name: "Niébé", nameEn: "Cowpea", pricePerKg: 700, category: "Céréales & Légumineuses", imageName: "suit.heart.fill", isSystemImage: true, wikipediaUrl: "https://fr.wikipedia.org/wiki/Ni%C3%A9b%C3%A9", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Black-eyed_peas_raw.jpg/320px-Black-eyed_peas_raw.jpg")
    ]
}
